### ISSUE TITLE
React rendering. 

### ISSUE THREAD

**Issue by baens** [slchackers/server-side-education#3]
Need to create a react rendering in ES5 and ES2015
## ES5
- [x] Basic express server rendering a div tag (PR #2)
- [x] Full HTML page render (PR #7)
- [ ] Component rendering ([WIP branch](https://github.com/slchackers/server-side-education/tree/es5-react-component))
- [ ] Routing 
- [ ] Component updating in browser ([WIP branch](https://github.com/slchackers/server-side-education/tree/es5-react-component))
- [ ] Unit tests
## ES2015
- [x] Basic express server rendering a div tag (PR #5)
- [x] JSX (PR #6)
- [ ] Full HTML page render (PR #8)
- [ ] Component rendering (PR #8)
- [ ] Routing 
- [ ] Component updating in browser (PR #8)
- [ ] Unit tests

**Comment by ghost** [comment]
Looks good :-)
